import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('Allegro pokazuje stan kanału bez udostępniania masowego mapowania', async () => {
  const source = await readFile(new URL('../src/frontend/12c-commerce-catalog-actions.js', import.meta.url), 'utf8');
  const sharedUi = await readFile(new URL('../src/frontend/08a-admin-responsive-layout.js', import.meta.url), 'utf8');
  const sharedStyle = await readFile(new URL('../src/styles/35-admin-unified-workspace.css', import.meta.url), 'utf8');
  const runtime = await readFile(new URL('../src/frontend/02-runtime-state.js', import.meta.url), 'utf8');
  assert.match(runtime, /filtrAllegroOfert="wszystkie", filtrStatusuAllegroOfert="sprzedaz"/);
  assert.match(source, /let allegroCentrumOfertTryb="publikacja"/);
  assert.match(source, /W sprzedaży \/ aktywne/);
  assert.match(source, /Do wystawienia i aktualizacji/);
  assert.match(source, /allegroDopasowanieOfertyMeta/);
  assert.match(source, /<th>Produkt<\/th><th>Identyfikacja<\/th><th>Gotowość<\/th><th>Cena<\/th><th>Kanał sprzedaży<\/th><th>Akcje<\/th>/);
  assert.match(source, /Oferta i produkt potwierdzone przez API/);
  assert.match(source, /Wstrzymane — brak u producenta/);
  assert.match(source, /Zakończone/);
  assert.match(source, /RZECZYWISTY STAN KANAŁU • API ALLEGRO/);
  assert.match(source, /Powiązania z produktami pozostają trwałe/);
  assert.match(source, /allegroCentrumOfertUstawTryb\('sprzedaz','sprzedaz'\)/);
  assert.match(source, /allegroOfertyZaznaczZakres\('strona',this\.checked\)/);
  assert.match(source, /deselectPage:"allegroOfertyZaznaczZakres\('strona',false\)"/);
  assert.match(source, /deselectAll:"allegroOfertyZaznaczZakres\('filtr',false\)"/);
  assert.doesNotMatch(source, /<b>Rejestr i powiązania<\/b>/);
  assert.doesNotMatch(source, /🧩 Połącz pewne/);
  assert.doesNotMatch(source, /<span>Stan powiązania<\/span>/);
  assert.match(source, /adminKanalStanApiHTML\(\{channel:"Allegro"/);
  assert.match(source, /adminKanalEtapyHTML\(\{id:"allegroOffersStageTitle"/);
  assert.match(source, /adminKanalEtapyHTML\(\{id:"allegroStageTitle"/);
  assert.match(source, /mapped=analizy\.filter\(item=>item\.mapped\)\.length/);
  assert.match(source, /tryb==="publikacja"\?allegroEtapyOfertHTML/);
  assert.match(source, /dataAttribute:"data-allegro-stage-filters"/);
  assert.match(source, /<colgroup><col class="allegro-publication-col-select"/);
  assert.match(source, /async function allegroPublikacjaUzgodnijZApi\(\)/);
  assert.match(source, /await allegroSynchronizujOferty\(\)/);
  assert.match(source, /allegroPublikacjaCentralnaUniewaznij\(\)/);
  assert.match(source, /allegroPublikacjaUzgodnienieBusy\?"Uzgadniam…":"↻ Uzgodnij z API"/);
  assert.match(sharedUi, /function adminKanalStanApiHTML/);
  assert.match(sharedUi, /function adminKanalEtapyHTML/);
  assert.match(sharedStyle, /\.admin-channel-truth\{display:grid/);
  assert.match(sharedStyle, /\.admin-channel-stage-filters\{display:grid/);
  assert.match(sharedStyle, /\.allegro-unified-offers .*\.allegro-listing-metrics\{display:none!important\}/);
});
